POST http://localhost:8000/products HTTP/1.1
Content-Type: application/json

{
    "name": "My Product 6",
    "price": 100.00
}

###

GET http://localhost:8000/products?page=1&limit=10 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2ODU5MTU0NzIsInN1YiI6ImM3ZTFiZTQ5LTI5ZjQtNDZmOC1hY2EyLWFlNTBhY2EyYmJmMCJ9.eBIQRZQRSgHx0zoWxluQadzEcyUxMHVrszJ-zGnfvDw

###

GET http://localhost:8000/products/a88a37fa-9495-4e8d-b5ce-28297b1a2db6 HTTP/1.1

###

PUT http://localhost:8000/products/a88a37fa-9495-4e8d-b5ce-28297b1a2db6 HTTP/1.1
Content-Type: application/json
    
    {
        "name": "My Product updated",
        "price": 1350.00
    }

###
DELETE  http://localhost:8000/products/a88a37fa-9495-4e8d-b5ce-28297b1a2db6 HTTP/1.1
