basePath: /
host: localhost:8000
info:
  contact:
    email: luizhjramos@outlook.com
    name: Luiz Henrique
    url: http://www.github.com/MogLuiz
  description: Product API with auhtentication
  termsOfService: http://swagger.io/terms/
  title: Key User API Example
  version: "1.0"
paths: {}
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
